vich_uploader:
    db_driver: orm

    mappings:
       manga:
           uri_prefix: /images/manga
           upload_destination: '%kernel.project_dir%/public/images/manga'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
